import { ArrowRightOutlined, CheckCircleOutlined, ExclamationCircleOutlined, FileExcelOutlined } from '@ant-design/icons';
import { Button, Card, Col, Row, Space, Statistic, Table, Tag, Typography } from 'antd';
import { history } from '@umijs/max';
import AsyncState from '@/components/AsyncState'; import PageHeader from '@/components/PageHeader'; import { useApi } from '@/hooks/useApi'; import { api } from '@/services/api';
const money=(v?:string)=>`¥${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2})}`;
export default function Workbench(){const o=useApi(api.overview,[]);const b=useApi(api.imports,[]);const metrics=o.data?.data.metrics;return <><PageHeader title="数据验证工作台" subtitle="从样本导入、质量校验到驾驶舱指标核对的最小闭环" mock={o.mock||b.mock}/><AsyncState loading={o.loading} error={o.error} onRetry={o.reload}><Row gutter={[16,16]}>{[
  ['当前可用现金',money(metrics?.availableCash),'待核对'],['本月预计回款',money(metrics?.expectedCollections),'待核对'],['本月计划支出',money(metrics?.plannedExpenses),'待核对'],['现金流缺口',money(metrics?.cashGap),'需关注']
].map(([t,v,s],i)=><Col xs={24} md={12} xl={6} key={t}><Card className="audit-card"><Statistic title={t} value={v} valueStyle={{color:i===3?'#c43d4f':'#17384a',fontSize:25}}/><Tag color={i===3?'red':'gold'}>{s}</Tag></Card></Col>)}</Row></AsyncState>
<Row gutter={16} style={{marginTop:18}}><Col xs={24} xl={16}><Card className="audit-card" title="最近导入批次" extra={<Button type="link" onClick={()=>history.push('/imports')}>查看全部 <ArrowRightOutlined/></Button>}><AsyncState loading={b.loading} error={b.error} empty={!b.data?.data.length} onRetry={b.reload}><Table pagination={false} rowKey="id" dataSource={b.data?.data} columns={[{title:'批次号',dataIndex:'batchNo'},{title:'文件',dataIndex:'fileName'},{title:'期间',render:(_,r)=>r.dataPeriodStart?`${r.dataPeriodStart} ~ ${r.dataPeriodEnd}`:'—'},{title:'质量',render:(_,r)=><Space><Tag color="green">{r.validRows||0} 有效</Tag>{!!r.errorRows&&<Tag color="red">{r.errorRows} 错误</Tag>}</Space>},{title:'操作',render:(_,r)=><Button onClick={()=>history.push(`/imports/${r.id}`)}>核对</Button>}]}/></AsyncState></Card></Col><Col xs={24} xl={8}><Card className="audit-card" title="验证进度"><Space direction="vertical" size={18}><Typography.Text><CheckCircleOutlined style={{color:'#2f9d6b'}}/> 标准数据契约 V0.1 已建立</Typography.Text><Typography.Text><CheckCircleOutlined style={{color:'#2f9d6b'}}/> 四类财务事实数据已覆盖</Typography.Text><Typography.Text><ExclamationCircleOutlined style={{color:'#d39219'}}/> 计算口径待 CFO 复核</Typography.Text><Button type="primary" icon={<FileExcelOutlined/>} onClick={()=>history.push('/imports')}>导入新样本</Button></Space></Card></Col></Row></>}
