"""V3 initial financial validation schema."""
from alembic import op
import sqlalchemy as sa

revision = "20260702_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("import_batch", sa.Column("batch_no", sa.String(40), nullable=False), sa.Column("file_name", sa.String(255), nullable=False), sa.Column("file_sha256", sa.String(64), nullable=False), sa.Column("template_version", sa.String(20), nullable=False), sa.Column("data_period_start", sa.Date(), nullable=False), sa.Column("data_period_end", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("total_rows", sa.Integer(), nullable=False), sa.Column("valid_rows", sa.Integer(), nullable=False), sa.Column("error_rows", sa.Integer(), nullable=False), sa.Column("warning_rows", sa.Integer(), nullable=False), sa.Column("uploaded_by", sa.String(100), nullable=False), sa.Column("published_by", sa.String(100)), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("review_note", sa.String(500)), sa.Column("version", sa.Integer(), nullable=False), sa.Column("id", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("batch_no"))
    op.create_index("ix_import_batch_file_sha256", "import_batch", ["file_sha256"]); op.create_index("ix_import_batch_status", "import_batch", ["status"])
    op.create_table("customer", sa.Column("customer_code", sa.String(64), nullable=False), sa.Column("customer_name", sa.String(200), nullable=False), sa.Column("customer_level", sa.String(20)), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("id", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("customer_code"))
    op.create_table("raw_import_row", sa.Column("import_batch_id", sa.Uuid(), nullable=False), sa.Column("sheet_name", sa.String(100), nullable=False), sa.Column("row_no", sa.Integer(), nullable=False), sa.Column("raw_data", sa.JSON(), nullable=False), sa.Column("normalized_data", sa.JSON()), sa.Column("validation_status", sa.String(16), nullable=False), sa.Column("validation_messages", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", sa.Uuid(), nullable=False), sa.ForeignKeyConstraint(["import_batch_id"], ["import_batch.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("import_batch_id", "sheet_name", "row_no"))
    common = [sa.Column("import_batch_id", sa.Uuid(), nullable=False), sa.Column("source_row_no", sa.Integer()), sa.Column("status", sa.String(20), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("id", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)]
    op.create_table("account_balance", sa.Column("account_code", sa.String(64), nullable=False), sa.Column("account_name", sa.String(120), nullable=False), sa.Column("snapshot_date", sa.Date(), nullable=False), sa.Column("available_balance", sa.Numeric(18,2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("restricted_amount", sa.Numeric(18,2), nullable=False), sa.Column("remark", sa.String(500)), *common, sa.ForeignKeyConstraint(["import_batch_id"], ["import_batch.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("account_code", "snapshot_date", "import_batch_id"))
    op.create_table("receivable", sa.Column("receivable_no", sa.String(64), nullable=False), sa.Column("customer_id", sa.Uuid(), nullable=False), sa.Column("business_ref_no", sa.String(64)), sa.Column("receivable_amount", sa.Numeric(18,2), nullable=False), sa.Column("agreed_due_date", sa.Date(), nullable=False), sa.Column("expected_date", sa.Date()), sa.Column("owner_code", sa.String(64), nullable=False), sa.Column("owner_name", sa.String(100), nullable=False), sa.Column("business_line", sa.String(100)), sa.Column("source_status", sa.String(20), nullable=False), sa.Column("remark", sa.String(500)), *[c._copy() for c in common], sa.ForeignKeyConstraint(["customer_id"], ["customer.id"]), sa.ForeignKeyConstraint(["import_batch_id"], ["import_batch.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("receivable_no", "import_batch_id"))
    op.create_table("collection", sa.Column("collection_no", sa.String(64), nullable=False), sa.Column("receivable_id", sa.Uuid(), nullable=False), sa.Column("collection_date", sa.Date(), nullable=False), sa.Column("collection_amount", sa.Numeric(18,2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("bank_reference", sa.String(100)), sa.Column("remark", sa.String(500)), *[c._copy() for c in common], sa.ForeignKeyConstraint(["receivable_id"], ["receivable.id"]), sa.ForeignKeyConstraint(["import_batch_id"], ["import_batch.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("collection_no"))
    op.create_table("planned_expense", sa.Column("expense_no", sa.String(64), nullable=False), sa.Column("expense_name", sa.String(200), nullable=False), sa.Column("category", sa.String(100), nullable=False), sa.Column("planned_date", sa.Date(), nullable=False), sa.Column("planned_amount", sa.Numeric(18,2), nullable=False), sa.Column("owner_code", sa.String(64), nullable=False), sa.Column("owner_name", sa.String(100), nullable=False), sa.Column("rigidity", sa.String(16), nullable=False), sa.Column("approval_status", sa.String(20), nullable=False), sa.Column("remark", sa.String(500)), *[c._copy() for c in common], sa.ForeignKeyConstraint(["import_batch_id"], ["import_batch.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("expense_no", "import_batch_id"))
    op.create_table("followup_record", sa.Column("receivable_id", sa.Uuid(), nullable=False), sa.Column("followed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("followed_by_code", sa.String(64), nullable=False), sa.Column("followed_by_name", sa.String(100), nullable=False), sa.Column("content", sa.String(1000), nullable=False), sa.Column("next_followup_date", sa.Date()), sa.Column("promised_collection_date", sa.Date()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", sa.Uuid(), nullable=False), sa.ForeignKeyConstraint(["receivable_id"], ["receivable.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("task", sa.Column("task_type", sa.String(32), nullable=False), sa.Column("source_type", sa.String(32), nullable=False), sa.Column("source_id", sa.Uuid()), sa.Column("title", sa.String(200), nullable=False), sa.Column("risk_level", sa.String(16), nullable=False), sa.Column("owner_code", sa.String(64)), sa.Column("owner_name", sa.String(100)), sa.Column("due_date", sa.Date(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("boss_intervention_required", sa.Boolean(), nullable=False), sa.Column("rule_version", sa.String(32), nullable=False), sa.Column("import_batch_id", sa.Uuid(), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("id", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.ForeignKeyConstraint(["import_batch_id"], ["import_batch.id"]), sa.PrimaryKeyConstraint("id"))
    for name, table, columns in [
        ("ix_raw_import_row_batch_status", "raw_import_row", ["import_batch_id", "validation_status"]),
        ("ix_account_balance_import_batch_id", "account_balance", ["import_batch_id"]), ("ix_account_balance_snapshot_date", "account_balance", ["snapshot_date"]),
        ("ix_receivable_import_batch_id", "receivable", ["import_batch_id"]), ("ix_receivable_customer_id", "receivable", ["customer_id"]), ("ix_receivable_owner_code", "receivable", ["owner_code"]), ("ix_receivable_due_status", "receivable", ["agreed_due_date", "source_status"]),
        ("ix_collection_import_batch_id", "collection", ["import_batch_id"]), ("ix_collection_receivable_id", "collection", ["receivable_id"]), ("ix_collection_collection_date", "collection", ["collection_date"]),
        ("ix_planned_expense_import_batch_id", "planned_expense", ["import_batch_id"]), ("ix_planned_expense_planned_date", "planned_expense", ["planned_date"]), ("ix_planned_expense_approval_status", "planned_expense", ["approval_status"]),
        ("ix_followup_record_receivable_id", "followup_record", ["receivable_id"]), ("ix_task_import_batch_id", "task", ["import_batch_id"]), ("ix_task_status_due_risk", "task", ["status", "due_date", "risk_level"]),
    ]:
        op.create_index(name, table, columns)


def downgrade():
    for table in ["task", "followup_record", "collection", "planned_expense", "receivable", "account_balance", "raw_import_row", "customer", "import_batch"]:
        op.drop_table(table)
